### ISSUE TITLE
マネージャーってどんなことしたらいいのか堤にアドバイスする会

### ISSUE THREAD

**Issue by shu223** [engineer-life/events#2]

**Comment by kenzan100** [comment]
傍聴者としての興味はすごくある。
アドバイスは自分にはできないので、誰がアドバイザとして手を挙げるのかめちゃくちゃ気になる

**Comment by shu223** [comment]
案メモ

- パネルディスカッション
  - 堤のお悩み・不安をお題として用意しておいて、パネルディスカッション的にマネージャー経験者の方々に回答してもらう
- エピソードトーク
  - 自分の上司／関わったマネージャーの良かったムーブ、悪かったムーブのエピソードを募集し、可能であれば話してもらう。
  - ラジオのはがき投稿みたいにテキストで投稿してもらって僕が読んでパネルディスカッションのお題にするのもありかも

**Comment by shu223** [comment]
こちら、3/27（日）19時〜で開催します！

**Comment by shu223** [comment]
開催しました！ #event_management
