### ISSUE TITLE
何でもコードリーディング会

### ISSUE THREAD

**Issue by hiroko-ino** [engineer-life/events#6]
ずっと構想していたことなのですが、インプットの時間を増やしたいなーと思っていて、みんなで各々好きなOSS（もしくは自分の業務のコードでもよし？）のコードを読んで、感想などをNotionなどに蓄積していくのってどうだろう。

- Notionのデータベースで読んだリポジトリを書いていくので、みんながどんなリポジトリを読んだかわかる
- いろんな強いエンジニアさんのコードリーディングの感想を見れて知見になる
- あんまり長い時間だとだれるので30分くらい？また、読むリポジトリがなくなったりするとあれなので隔週とか。

まだ私の適当な妄想でしかないですが、何かこうしたらいいんじゃないか？みたいなコメントですとか、色々いただけると嬉しいです！

**Comment by kenzan100** [comment]
すごい良さそう

**Comment by shu223** [comment]
2/28に一度開催されたのでクローズします！
第2回も開催される予定で、詳細は #club_もくもくコードリーディング会 にて！
