### ISSUE TITLE
ガチ読書会（ゆる読書会ロングバージョン）

### ISSUE THREAD

**Issue by shu223** [engineer-life/events#9]
`30分読書 + シェアタイム` で運用されている #club_ゆる読書会 のロングバージョン。

案

```
3時間読書 + シェアタイム
```

or

```
(30分 + シェアタイム) * 3セット 
```

- シェアタイムは希望者のみ（他薦ok）
- 休日の日中にやるイメージ

**Comment by nabettu** [comment]
いいですね！
フォーマットそのまま流用出来るのでファシリテーターは準備いらないですね💪

**Comment by shu223** [comment]
意外と需要なさそう & 言い出しっぺの私が開催する余裕はなさそうなのでいったんクローズします！
